ETHEREUM_AVERAGE_SECONDS_PER_BLOCK = 12

# Starknet L1 Core Contract address on Ethereum mainnet
# Source: crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
STARKNET_L1_CONTRACT_ADDRESS = "0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4"

# Event signatures (auto-generated by Rust sol! macro from ABI)
# Source: crates/papyrus_base_layer/src/constants.rs
# ABI: crates/papyrus_base_layer/resources/Starknet-0.10.3.4.json
LOG_MESSAGE_TO_L2_EVENT_SIGNATURE = (
    "0xdb80dd488acf86d17c747445b0eabb5d57c541d3bd7b6b87af987858e5066b2b"
)

# Function selectors for Starknet L1 contract.
STATE_BLOCK_NUMBER_SELECTOR = "0x35befa5d"  # stateBlockNumber()
STATE_BLOCK_HASH_SELECTOR = "0x382d83e3"  # stateBlockHash()
