image:
  repository: ghcr.io/starkware-libs/sequencer/sequencer
  tag: APOLLO-0.14.2-RC.7
  imagePullPolicy: IfNotPresent

config:
  sequencerConfig:
    chain_id: SN_INTEGRATION_SEPOLIA
    eth_fee_token_address: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7'
    native_classes_whitelist: All
    starknet_url: https://feeder.integration-sepolia.starknet.io/
    strk_fee_token_address: '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d'
    versioned_constants_overrides.max_n_events: 1000

env:
- name: RUST_LOG
  value: debug
- name: RUST_BACKTRACE
  value: full
- name: NO_COLOR
  value: '1'
