image:
  repository: ghcr.io/starkware-libs/sequencer/sequencer
  tag: APOLLO-0.14.2-RC.5
  imagePullPolicy: IfNotPresent

env:
- name: RUST_LOG
  value: debug
- name: RUST_BACKTRACE
  value: full
- name: NO_COLOR
  value: '1'
