include:
  - configs/overlays/hybrid/testing/node-0/common.yaml

name: committer

replicas: 1

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: committer
    port: 55013
    targetPort: 55013
    protocol: TCP

statefulSet:
  enabled: true

persistentVolume:
  enabled: true
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  mountPath: /data
  size: 2Gi
  storageClass: ""
