# Fragment: statefulSet + persistentVolume
statefulSet:
  enabled: true

persistentVolume:
  enabled: true
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  mountPath: /data
  size: 2Gi
  storageClass: ""
