# Core service (paths relative to deployment base_dir)
include:
  - configs/overlays/hybrid/testing/node-0/common.yaml

name: core

replicas: 1

config:
  configList: crates/apollo_deployments/resources/services/hybrid/replacer_deployment_core.json

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: batcher
    port: 55000
    targetPort: 55000
    protocol: TCP
  - name: class-manager
    port: 55001
    targetPort: 55001
    protocol: TCP
  - name: consensus-p2p
    port: 53080
    targetPort: 53080
    protocol: TCP
  - name: signature-manager
    port: 55008
    targetPort: 55008
    protocol: TCP
  - name: state-sync-network
    port: 55010
    targetPort: 55010
    protocol: TCP
  - name: state-sync-rpc
    port: 55009
    targetPort: 55009
    protocol: TCP
  - name: batcher-storage-reader
    port: 55011
    targetPort: 55011
    protocol: TCP
  - name: state-sync-storage-reader
    port: 55014
    targetPort: 55014
    protocol: TCP
  - name: class-manager-storage-reader
    port: 55210
    targetPort: 55210
    protocol: TCP

statefulSet:
  enabled: true

persistentVolume:
  enabled: true
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  mountPath: /data
  size: 2Gi
  storageClass: ""
