include:
  - configs/overlays/hybrid/testing/node-0/common.yaml

name: l1

replicas: 1

config:
  configList: crates/apollo_deployments/resources/services/hybrid/replacer_deployment_l1.json

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: l1-endpoint-monitoring
    port: 55005
    targetPort: 55005
    protocol: TCP
  - name: l1-gas-price-provider
    port: 55003
    targetPort: 55003
    protocol: TCP
  - name: l1-provider
    port: 55004
    targetPort: 55004
    protocol: TCP
