apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: __PROMETHEUS_URL__
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"
