{
 "title": "Sequencer Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "batcher_proposal_started",
     "type": "stat",
     "description": "Counter of proposals started",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_started" }
     ]
    },
    {
     "title": "batcher_proposal_succeeded",
     "type": "stat",
     "description": "Counter of successful proposals",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_succeeded" }
     ]
    },
    {
     "title": "batcher_proposal_failed",
     "type": "stat",
     "description": "Counter of failed proposals",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_failed" }
     ]
    },
    {
     "title": "batcher_batched_transactions",
     "type": "stat",
     "description": "Counter of batched transactions across all forks",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_batched_transactions" }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "consensus_block_number",
     "type": "stat",
     "description": "The block number consensus is working to decide",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_block_number" }
     ]
    },
    {
     "title": "consensus_round",
     "type": "stat",
     "description": "The round of the state machine",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_round" }
     ]
    },
    {
     "title": "consensus_max_cached_block_number",
     "type": "stat",
     "description": "How many blocks after current are cached",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_max_cached_block_number"
      }
     ]
    },
    {
     "title": "consensus_cached_votes",
     "type": "stat",
     "description": "How many votes are cached when starting to work on a new block number",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_cached_votes" }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_consensus",
     "type": "stat",
     "description": "The total number of decisions reached by way of consensus",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_consensus"
      }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_sync",
     "type": "stat",
     "description": "The total number of decisions reached by way of sync",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_sync"
      }
     ]
    },
    {
     "title": "consensus_proposals_received",
     "type": "stat",
     "description": "The total number of proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_received" }
     ]
    },
    {
     "title": "consensus_proposals_valid_init",
     "type": "stat",
     "description": "The total number of proposals received with a valid init",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_valid_init" }
     ]
    },
    {
     "title": "consensus_proposals_validated",
     "type": "stat",
     "description": "The total number of complete, valid proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_validated" }
     ]
    },
    {
     "title": "consensus_proposals_invalid",
     "type": "stat",
     "description": "The total number of proposals that failed validation",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_invalid" }
     ]
    },
    {
     "title": "consensus_build_proposal_total",
     "type": "stat",
     "description": "The total number of proposals built",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_build_proposal_total" }
     ]
    },
    {
     "title": "consensus_build_proposal_failed",
     "type": "stat",
     "description": "The number of proposals that failed to be built",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_build_proposal_failed"
      }
     ]
    },
    {
     "title": "consensus_reproposals",
     "type": "stat",
     "description": "The number of reproposals sent",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_reproposals" }
     ]
    },
    {
     "title": "consensus_new_value_locks",
     "type": "stat",
     "description": "The number of times consensus has attained a lock on a new value",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_new_value_locks" }
     ]
    },
    {
     "title": "consensus_held_locks",
     "type": "stat",
     "description": "The number of times consensus progressed to a new round while holding a lock",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_held_locks" }
     ]
    },
    {
     "title": "consensus_timeouts",
     "type": "stat",
     "description": "The number of times consensus has timed out",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (timeout_reason) (consensus_timeouts)"
      }
     ]
    },
    {
     "title": "consensus_num_batches_in_proposal",
     "type": "stat",
     "description": "The number of transaction batches in a valid proposal received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_num_batches_in_proposal"
      }
     ]
    },
    {
     "title": "consensus_num_txs_in_proposal",
     "type": "stat",
     "description": "The total number of individual transactions in a valid proposal received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_num_txs_in_proposal" }
     ]
    },
    {
     "title": "consensus_l2_gas_price",
     "type": "stat",
     "description": "The L2 gas price calculated in an accepted proposal",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_l2_gas_price" }
     ]
    },
    {
     "title": "cende_last_prepared_blob_block_number",
     "type": "stat",
     "description": "The blob block number that cende knows. That means the sequencer can be the proposer only if the current height is greater by one than this value.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cende_last_prepared_blob_block_number"
      }
     ]
    },
    {
     "title": "cende_prepare_blob_for_next_height_latency",
     "type": "stat",
     "description": "The time it takes to prepare the blob for the next height, i.e create the blob object.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(cende_prepare_blob_for_next_height_latency[2m])"
      }
     ]
    },
    {
     "title": "cende_write_prev_height_blob_latency",
     "type": "stat",
     "description": "Be careful with this metric, if the blob was already written by another request, the latency is much lower since wirting to Aerospike is not needed.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(cende_write_prev_height_blob_latency[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_server_added_transactions_total",
     "type": "stat",
     "description": "Total number of transactions added",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_server_added_transactions_total"
      }
     ]
    }
   ]
  },
  {
   "title": "State Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_state_sync_processed_transactions",
     "type": "stat",
     "description": "The number of transactions processed by the state sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_processed_transactions"
      }
     ]
    },
    {
     "title": "apollo_state_sync_reverted_transactions",
     "type": "stat",
     "description": "The number of transactions reverted by the state sync component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_reverted_transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "MempoolP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_mempool_p2p_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_received_messages"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_broadcasted_transaction_batch_size",
     "type": "stat",
     "description": "The number of transactions in batches broadcast by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_broadcasted_transaction_batch_size"
      }
     ]
    }
   ]
  },
  {
   "title": "ConsensusP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_consensus_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the consensus p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_received_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_received_messages"
      }
     ]
    }
   ]
  },
  {
   "title": "StateSyncP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_p2p_sync_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_p2p_sync_num_active_inbound_sessions",
     "type": "stat",
     "description": "The number of inbound sessions to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_active_inbound_sessions"
      }
     ]
    },
    {
     "title": "apollo_p2p_sync_num_active_outbound_sessions",
     "type": "stat",
     "description": "The number of outbound sessions to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_active_outbound_sessions"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_received) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (source) (gateway_transactions_received) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the gateway during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(gateway_transactions_received[20m])) or vector(0)"
      }
     ]
    },
    {
     "title": "gateway_add_tx_latency",
     "type": "graph",
     "description": "Latency of gateway add_tx function in secs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(gateway_add_tx_latency[2m])"
      }
     ]
    },
    {
     "title": "gateway_validate_tx_latency",
     "type": "graph",
     "description": "Latency of gateway validate function in secs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(gateway_validate_tx_latency[2m])"
      }
     ]
    },
    {
     "title": "gateway_transactions_failed",
     "type": "stat",
     "description": "Counter of failed transactions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_failed)"
      }
     ]
    },
    {
     "title": "gateway_transactions_sent_to_mempool",
     "type": "stat",
     "description": "Counter of transactions sent to the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_sent_to_mempool)"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received by the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (mempool_transactions_received)"
      }
     ]
    },
    {
     "title": "mempool_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the mempool during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(mempool_transactions_received[20m])) or vector(0)"
      }
     ]
    },
    {
     "title": "mempool_transactions_dropped",
     "type": "stat",
     "description": "Counter of transactions dropped from the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (drop_reason) (mempool_transactions_dropped)"
      }
     ]
    },
    {
     "title": "mempool_txs_committed",
     "type": "stat",
     "description": "The number of transactions that were committed to block",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_txs_committed" }
     ]
    },
    {
     "title": "mempool_pool_size",
     "type": "graph",
     "description": "The average size of the pool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pool_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_priority_queue_size",
     "type": "graph",
     "description": "The average size of the priority queue",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_priority_queue_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_pending_queue_size",
     "type": "graph",
     "description": "The average size of the pending queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pending_queue_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_total_size_bytes",
     "type": "graph",
     "description": "The average total transaction size in bytes over time in the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_total_size_bytes[2m])"
      }
     ]
    },
    {
     "title": "mempool_get_txs_size",
     "type": "graph",
     "description": "The average size of the get_txs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_get_txs_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_delayed_declare_size",
     "type": "graph",
     "description": "The average number of delayed declare transactions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_delayed_declare_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_transaction_time_spent",
     "type": "graph",
     "description": "The time (secs) that a transaction spent in the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_transaction_time_spent[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Apollo State Reader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "class_cache_miss_ratio",
     "type": "graph",
     "description": "The ratio of cache misses when requesting compiled classes from the apollo state reader",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "100 * (rate(class_cache_misses[5m]) / (rate(class_cache_misses[5m]) + rate(class_cache_hits[5m])))"
      }
     ]
    },
    {
     "title": "native_class_returned_ratio",
     "type": "graph",
     "description": "The ratio of Native classes returned by the apollo state reader",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "100 * (rate(native_class_returned[5m]) / (rate(class_cache_hits[5m]) + rate(class_cache_misses[5m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Batcher Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "batcher_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by batcher local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_local_msgs_received" }
     ]
    },
    {
     "title": "batcher_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by batcher local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_local_msgs_processed" }
     ]
    },
    {
     "title": "batcher_local_queue_depth",
     "type": "stat",
     "description": "The depth of the batcher's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_local_queue_depth" }
     ]
    },
    {
     "title": "batcher_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_remote_msgs_received" }
     ]
    },
    {
     "title": "batcher_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "batcher_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_remote_msgs_processed" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "gateway_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by gateway local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gateway_local_msgs_received" }
     ]
    },
    {
     "title": "gateway_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by gateway local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gateway_local_msgs_processed" }
     ]
    },
    {
     "title": "gateway_local_queue_depth",
     "type": "stat",
     "description": "The depth of the gateway's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gateway_local_queue_depth" }
     ]
    },
    {
     "title": "gateway_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gateway_remote_msgs_received" }
     ]
    },
    {
     "title": "gateway_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "gateway_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gateway_remote_msgs_processed" }
     ]
    }
   ]
  },
  {
   "title": "Class Manager Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "class_manager_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by class manager local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_msgs_received"
      }
     ]
    },
    {
     "title": "class_manager_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by class manager local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_msgs_processed"
      }
     ]
    },
    {
     "title": "class_manager_local_queue_depth",
     "type": "stat",
     "description": "The depth of the class manager's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_queue_depth"
      }
     ]
    },
    {
     "title": "class_manager_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_msgs_received"
      }
     ]
    },
    {
     "title": "class_manager_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "class_manager_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_msgs_processed"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 Provider Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "l1_provider_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by L1 provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_local_msgs_received"
      }
     ]
    },
    {
     "title": "l1_provider_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by L1 provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_local_msgs_processed"
      }
     ]
    },
    {
     "title": "l1_provider_local_queue_depth",
     "type": "stat",
     "description": "The depth of the L1 provider's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "l1_provider_local_queue_depth" }
     ]
    },
    {
     "title": "l1_provider_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_msgs_received"
      }
     ]
    },
    {
     "title": "l1_provider_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "l1_provider_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_msgs_processed"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 Gas Price Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "l1_gas_price_provider_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by L1 gas price provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_msgs_received"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by L1 gas price provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_msgs_processed"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_local_queue_depth",
     "type": "stat",
     "description": "The depth of the L1 gas price provider's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_queue_depth"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_msgs_received"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_msgs_processed"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by mempool local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_local_msgs_received" }
     ]
    },
    {
     "title": "mempool_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by mempool local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_local_msgs_processed" }
     ]
    },
    {
     "title": "mempool_local_queue_depth",
     "type": "stat",
     "description": "The depth of the mempool's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_local_queue_depth" }
     ]
    },
    {
     "title": "mempool_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_remote_msgs_received" }
     ]
    },
    {
     "title": "mempool_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "mempool_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_remote_msgs_processed" }
     ]
    }
   ]
  },
  {
   "title": "MempoolP2pInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_p2p_propagator_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by mempool p2p local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 293 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_msgs_received"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by mempool p2p local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 293 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_msgs_processed"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_local_queue_depth",
     "type": "stat",
     "description": "The depth of the mempool p2p's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_queue_depth"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_msgs_received"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_msgs_processed"
      }
     ]
    }
   ]
  },
  {
   "title": "SierraCompilerInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "sierra_compiler_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by sierra compiler local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_msgs_received"
      }
     ]
    },
    {
     "title": "sierra_compiler_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by sierra compiler local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_msgs_processed"
      }
     ]
    },
    {
     "title": "sierra_compiler_local_queue_depth",
     "type": "stat",
     "description": "The depth of the sierra compiler's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_queue_depth"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_msgs_received"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 324 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 324 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_msgs_processed"
      }
     ]
    }
   ]
  },
  {
   "title": "Compile sierra to casm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "compile_to_casm_compilation_duration",
     "type": "graph",
     "description": "Server-side compilation to casm duration in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(compile_to_casm_compilation_duration[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "StateSyncInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "state_sync_local_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by state sync local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 332 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "state_sync_local_msgs_received" }
     ]
    },
    {
     "title": "state_sync_local_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by state sync local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 332 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_local_msgs_processed"
      }
     ]
    },
    {
     "title": "state_sync_local_queue_depth",
     "type": "stat",
     "description": "The depth of the state sync's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "state_sync_local_queue_depth" }
     ]
    },
    {
     "title": "state_sync_remote_msgs_received",
     "type": "stat",
     "description": "Counter of messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_msgs_received"
      }
     ]
    },
    {
     "title": "state_sync_remote_valid_msgs_received",
     "type": "stat",
     "description": "Counter of valid messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 344 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_valid_msgs_received"
      }
     ]
    },
    {
     "title": "state_sync_remote_msgs_processed",
     "type": "stat",
     "description": "Counter of messages processed by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 344 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_msgs_processed"
      }
     ]
    }
   ]
  }
 ]
}