name: gateway
config:
  configList: crates/apollo_deployments/resources/services/hybrid/replacer_deployment_gateway.json

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: gateway
    port: 55002
    targetPort: 55002
    protocol: TCP
  - name: http-server
    port: 8080
    targetPort: 8080
    protocol: TCP
