{
 "title": "Papyrus-node-data",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(papyrus_header_marker, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(papyrus_header_marker{kubernetes_namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "version", "query": "V0_8" }
  ]
 },
 "panels": [
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Header Latency",
   "type": "timeseries",
   "description": "The difference, in seconds, between the time the node received the batch and the batch creation timestamp.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "papyrus_header_latency{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Starknet Block Number",
   "type": "stat",
   "description": "The Current Starknet block number.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "L1 Block Number",
   "type": "stat",
   "description": "The block number of the last Starknet block that was finalized on L1.",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apollo_base_layer_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "L1 Block Number Diff",
   "type": "stat",
   "description": "The difference between Starknet Block Number and L1 Block Number.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} - apollo_base_layer_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Header",
   "type": "stat",
   "description": "The current block header marker.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_header_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Body",
   "type": "stat",
   "description": "The current block body marker.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_body_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "State Update",
   "type": "stat",
   "description": "The current state update marker.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_state_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Compiled Class (CASM)",
   "type": "stat",
   "description": "The current compiled class marker.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_compiled_class_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Header Diff",
   "type": "stat",
   "description": "The difference between the current Starknet block number and the current block header marker.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} - papyrus_header_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Body Diff",
   "type": "stat",
   "description": "The difference between the current Starknet block number and the current block body marker.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} - papyrus_body_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "State Update Diff",
   "type": "stat",
   "description": "The difference between the current Starknet block number and the current state update marker.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} - papyrus_state_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Compiled Class (CASM) Diff",
   "type": "stat",
   "description": "The difference between the current Starknet block number and the current compiled class marker.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} - papyrus_compiled_class_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Header %",
   "type": "stat",
   "description": "The percentage of the current block header marker from the current Starknet block number.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_header_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "Block Body %",
   "type": "stat",
   "description": "The percentage of the current block body marker from the current Starknet block number.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_body_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "State Update %",
   "type": "stat",
   "description": "The percentage of the current state update marker from the current Starknet block number.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_state_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "Compiled Class (CASM) %",
   "type": "stat",
   "description": "The percentage of the current compiled class marker from the current Starknet block number.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_compiled_class_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=~\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  { "title": "Resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage percentage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container, pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "description": "Storage usage in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Networking usage",
   "type": "timeseries",
   "description": "Networking usage.\nTx - Transmitting.\nRx - Receiving.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (container, pod)",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (container, pod)",
     "legendFormat": "Rx"
    }
   ]
  },
  { "title": "Requests and latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "blockNumber Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockNumber\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "blockNumber Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockNumber\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "blockNumber Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockNumber\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "blockNumber Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockNumber\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getNonce Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getNonce\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getNonce Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getNonce\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getNonce Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getNonce\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getNonce Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getNonce\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getStateUpdate Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStateUpdate\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getStateUpdate Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStateUpdate\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getStateUpdate Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStateUpdate\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getStateUpdate Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStateUpdate\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getTransactionByHash Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByHash\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getTransactionByHash Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByHash\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getTransactionByHash Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByHash\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getTransactionByHash Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByHash\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getClass Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClass\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getClass Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClass\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getClass Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClass\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getClass Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClass\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getEvents Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getEvents\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getEvents Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getEvents\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getEvents Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getEvents\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getEvents Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getNonce\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getClassAt Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassAt\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getClassAt Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassAt\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getClassAt Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassAt\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getClassAt Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassAt\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getClassHashAt Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassHashAt\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getClassHashAt Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassHashAt\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getClassHashAt Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassHashAt\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getClassHashAt Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getClassHashAt\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getBlockWithTxs Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxs\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getBlockWithTxs Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxs\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getBlockWithTxs Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxs\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getBlockWithTxs Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxs\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getStorageAt Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStorageAt\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getStorageAt Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStorageAt\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getStorageAt Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStorageAt\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getStorageAt Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getStorageAt\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockTransactionCount\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockTransactionCount\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockTransactionCount\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockTransactionCount\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getTransactionReceipt Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionReceipt\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getTransactionReceipt Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionReceipt\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getTransactionReceipt Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionReceipt\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getTransactionReceipt Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionReceipt\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxHashes\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxHashes\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxHashes\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getBlockWithTxHashes\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "getTransactionByBlockIdAndIndex Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByBlockIdAndIndex\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "getTransactionByBlockIdAndIndex Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByBlockIdAndIndex\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "getTransactionByBlockIdAndIndex Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByBlockIdAndIndex\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "getTransactionByBlockIdAndIndex Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"getTransactionByBlockIdAndIndex\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "blockHashAndNumber Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockHashAndNumber\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "blockHashAndNumber Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockHashAndNumber\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "blockHashAndNumber Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockHashAndNumber\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "blockHashAndNumber Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"blockHashAndNumber\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "chainId Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"chainId\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "chainId Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"chainId\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "chainId Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"chainId\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "chainId Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"chainId\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "syncing Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"syncing\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "syncing Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"syncing\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "syncing Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"syncing\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "syncing Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"syncing\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "call Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"call\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "call Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"call\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "call Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"call\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "call Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"call\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "simulateTransactions Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"simulateTransactions\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "simulateTransactions Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"simulateTransactions\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "simulateTransactions Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"simulateTransactions\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "simulateTransactions Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"simulateTransactions\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "estimateFee Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"estimateFee\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "estimateFee Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"estimateFee\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "estimateFee Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"estimateFee\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "estimateFee Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"estimateFee\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "traceTransaction Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceTransaction\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "traceTransaction Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceTransaction\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "traceTransaction Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceTransaction\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "traceTransaction Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceTransaction\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "traceBlockTransactions Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceBlockTransactions\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "traceBlockTransactions Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceBlockTransactions\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "traceBlockTransactions Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceBlockTransactions\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "traceBlockTransactions Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"traceBlockTransactions\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "addInvokeTransaction Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addInvokeTransaction\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeployAccountTransaction\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeployAccountTransaction\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeployAccountTransaction\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeployAccountTransaction\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "addDeclareTransaction Requests",
   "type": "stat",
   "description": "Number of incoming requests.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_incoming_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeclareTransaction\",version=\"$version\"}",
     "legendFormat": "Incoming requests"
    }
   ]
  },
  {
   "title": "addDeclareTransaction Failed Requests",
   "type": "stat",
   "description": "Number of failed requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_failed_requests{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeclareTransaction\",version=\"$version\"}",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "addDeclareTransaction Latency (0.95)",
   "type": "stat",
   "description": "The maximal latency of the quickest 95% of the requests.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeclareTransaction\",version=\"$version\",quantile=\"0.95\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "addDeclareTransaction Latencies",
   "type": "timeseries",
   "description": "The maximal latencies of different percentages of the quickest requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"$namespace\", pod=~\"$pod\", method=\"addDeclareTransaction\",version=\"$version\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}