[package]
name = "apollo_rpc_types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared JSON-RPC error types for Starknet API."

[lints]
workspace = true

[dependencies]
jsonrpsee-types.workspace = true
serde = { workspace = true, features = ["derive"] }
