from enum import Enum


# k8s service types
class K8SServiceType(str, Enum):
    CLUSTER_IP = "ClusterIP"
    LOAD_BALANCER = "LoadBalancer"
    NODE_PORT = "NodePort"


MONITORING_ENDPOINT_PORT_NAME = "monitoring-endpoint"
MONITORING_ENDPOINT_PORT_NUMBER = 8082
MONITORING_METRICS_ENDPOINT = "/monitoring/metrics"
PROBE_MONITORING_READY_PATH = "/monitoring/ready"
PROBE_MONITORING_ALIVE_PATH = "/monitoring/alive"
PROBE_FAILURE_THRESHOLD = 5
PROBE_PERIOD_SECONDS = 10
PROBE_TIMEOUT_SECONDS = 5
BACKEND_CONFIG_CONNECTION_DRAINING_SECONDS = 60
BACKEND_CONFIG_TIMEOUT_SECONDS = 30
BACKEND_CONFIG_HEALTH_CHECK_INTERVAL_SECONDS = 10
BACKEND_CONFIG_HEALTH_CHECK_TIMEOUT_SECONDS = 5
BACKEND_CONFIG_HEALTHY_THRESHOLD = 1
BACKEND_CONFIG_UNHEALTHY_THRESHOLD = 10

PVC_STORAGE_CLASS_NAME = "premium-rwo"
PVC_VOLUME_MODE = "Filesystem"
PVC_ACCESS_MODE = ["ReadWriteOnce"]

HPA_MIN_REPLICAS = 1
HPA_MAX_REPLICAS = 100

SECRETS_FILE_NAME = "secrets.json"
SECRETS_MOUNT_PATH = "/etc/secrets"
