use papyrus_test_utils::{
    auto_impl_get_test_instance,
    get_number_of_variants,
    get_rng,
    GetTestInstance,
};
use rand::Rng;
use starknet_api::block::BlockHash;
use starknet_api::core::ContractAddress;
use starknet_api::execution_resources::GasAmount;
use starknet_api::transaction::{
    DeclareTransaction,
    DeclareTransactionV3,
    DeployAccountTransaction,
    DeployAccountTransactionV3,
    InvokeTransaction,
    InvokeTransactionV3,
    Transaction,
    ValidResourceBounds,
};

use crate::consensus::{
    ConsensusMessage,
    Proposal,
    StreamMessage,
    StreamMessageBody,
    Vote,
    VoteType,
};

auto_impl_get_test_instance! {
    pub enum ConsensusMessage {
        Proposal(Proposal) = 0,
        Vote(Vote) = 1,
    }
}

auto_impl_get_test_instance! {
    pub struct Proposal {
        pub height: u64,
        pub round: u32,
        pub proposer: ContractAddress,
        pub transactions: Vec<Transaction>,
        pub block_hash: BlockHash,
        pub valid_round: Option<u32>,
    }
}

auto_impl_get_test_instance! {
    pub struct Vote {
        pub vote_type: VoteType,
        pub height: u64,
        pub round: u32,
        pub block_hash: Option<BlockHash>,
        pub voter: ContractAddress,
    }
}

auto_impl_get_test_instance! {
    pub enum VoteType {
        Prevote = 0,
        Precommit = 1,
    }
}

// The auto_impl_get_test_instance macro does not work for StreamMessage because it has
// a generic type. TODO(guyn): try to make the macro work with generic types.
impl GetTestInstance for StreamMessage<ConsensusMessage> {
    fn get_test_instance(rng: &mut rand_chacha::ChaCha8Rng) -> Self {
        let message = if rng.gen_bool(0.5) {
            StreamMessageBody::Content(ConsensusMessage::Proposal(Proposal::get_test_instance(rng)))
        } else {
            StreamMessageBody::Fin
        };
        Self { message, stream_id: rng.gen_range(0..100), message_id: rng.gen_range(0..1000) }
    }
}

#[test]
fn convert_stream_message_to_vec_u8_and_back() {
    let mut rng = get_rng();

    // Test that we can convert a StreamMessage with a ConsensusMessage message to bytes and back.
    let stream_message: StreamMessage<ConsensusMessage> =
        StreamMessage::get_test_instance(&mut rng);

    let bytes_data: Vec<u8> = stream_message.clone().into();
    let res_data = StreamMessage::try_from(bytes_data).unwrap();
    assert_eq!(stream_message, res_data);
}

#[test]
fn convert_consensus_message_to_vec_u8_and_back() {
    let mut rng = get_rng();

    // Test that we can convert a ConsensusMessage to bytes and back.
    let message = ConsensusMessage::get_test_instance(&mut rng);

    let bytes_data: Vec<u8> = message.clone().into();
    let res_data = ConsensusMessage::try_from(bytes_data).unwrap();
    assert_eq!(message, res_data);
}

#[test]
fn convert_vote_to_vec_u8_and_back() {
    let mut rng = get_rng();

    let vote = Vote::get_test_instance(&mut rng);

    let bytes_data: Vec<u8> = vote.clone().into();
    let res_data = Vote::try_from(bytes_data).unwrap();
    assert_eq!(vote, res_data);
}

#[test]
fn convert_proposal_to_vec_u8_and_back() {
    let mut rng = get_rng();

    let mut proposal = Proposal::get_test_instance(&mut rng);

    // Below is a hack: The problem is that when we deserialize a Transaction, if it has an
    // AllResources variant, it will turn into a L1Gas variant if all the gas prices are zero.
    // So I will intentionally make them non-zero, but the real solution is to make the randomly
    // generated structs contain random values instead of zero.
    // TODO(guyn): add random values to the structs generated by get_test_instance
    let transaction = &mut proposal.transactions[0];
    match transaction {
        Transaction::Declare(DeclareTransaction::V3(DeclareTransactionV3 {
            resource_bounds,
            ..
        }))
        | Transaction::Invoke(InvokeTransaction::V3(InvokeTransactionV3 {
            resource_bounds, ..
        }))
        | Transaction::DeployAccount(DeployAccountTransaction::V3(DeployAccountTransactionV3 {
            resource_bounds,
            ..
        })) => {
            if let ValidResourceBounds::AllResources(ref mut bounds) = resource_bounds {
                bounds.l2_gas.max_amount = GasAmount(1);
            }
        }
        _ => {}
    }

    let bytes_data: Vec<u8> = proposal.clone().into();
    let res_data = Proposal::try_from(bytes_data).unwrap();
    assert_eq!(proposal, res_data);
}
