name: "Setup Namespace Cache"
description: "Use Namespace actions to setup cache"

runs:
  using: "composite"
  steps:
    - name: Mount namespace cache volume for rust
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          /home/runner/.cargo
          /home/runner/.cache/sccache

    - name: Configure sccache
      shell: bash
      run: |
        SCCACHE_DIR=/home/runner/.cache/sccache
        SCCACHE_CACHE_SIZE=50G
        mkdir -p "${SCCACHE_DIR}"
        echo "SCCACHE_DIR=${SCCACHE_DIR}" >> "$GITHUB_ENV"
        echo "SCCACHE_CACHE_SIZE=${SCCACHE_CACHE_SIZE}" >> "$GITHUB_ENV"

    - name: Mount namespace cache volume for python
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        cache: python
