{
 "title": "Sequencer Node Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(batcher_proposal_started,namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(batcher_proposal_started,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Batcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "batcher_proposal_failed",
     "type": "stat",
     "description": "Counter of failed proposals",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_proposal_failed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_proposal_started",
     "type": "stat",
     "description": "Counter of proposals started",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_proposal_started{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_proposal_succeeded",
     "type": "stat",
     "description": "Counter of successful proposals",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_proposal_succeeded{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_proposal_failed",
     "type": "stat",
     "description": "Counter of failed proposals",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_proposal_failed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_batched_transactions",
     "type": "stat",
     "description": "Counter of batched transactions across all forks",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_batched_transactions{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "consensus_block_number",
     "type": "graph",
     "description": "The block number consensus is working to decide",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_block_number{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_round",
     "type": "graph",
     "description": "The round of the state machine",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_round{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Average consensus round",
     "type": "graph",
     "description": "Average consensus round (10m)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(consensus_round{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])"
      }
     ]
    },
    {
     "title": "consensus_max_cached_block_number",
     "type": "graph",
     "description": "How many blocks after current are cached",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_max_cached_block_number{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_cached_votes",
     "type": "graph",
     "description": "How many votes are cached when starting to work on a new block number",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_cached_votes{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_consensus",
     "type": "graph",
     "description": "The total number of decisions reached by way of consensus",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_consensus{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_sync",
     "type": "graph",
     "description": "The total number of decisions reached by way of sync",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_sync{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_proposals_received",
     "type": "graph",
     "description": "The total number of proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_proposals_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_proposals_valid_init",
     "type": "graph",
     "description": "The total number of proposals received with a valid init",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_proposals_valid_init{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_proposals_validated",
     "type": "graph",
     "description": "The total number of complete, valid proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_proposals_validated{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_proposals_invalid",
     "type": "graph",
     "description": "The total number of proposals that failed validation",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_proposals_invalid{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_build_proposal_total",
     "type": "graph",
     "description": "The total number of proposals built",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_build_proposal_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_build_proposal_failed",
     "type": "graph",
     "description": "The number of proposals that failed to be built",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_build_proposal_failed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_reproposals",
     "type": "graph",
     "description": "The number of reproposals sent",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_reproposals{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_new_value_locks",
     "type": "graph",
     "description": "The number of times consensus has attained a lock on a new value",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_new_value_locks{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_held_locks",
     "type": "graph",
     "description": "The number of times consensus progressed to a new round while holding a lock",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_held_locks{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_timeouts",
     "type": "graph",
     "description": "The number of times consensus has timed out",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (timeout_reason) (consensus_timeouts{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "consensus_num_batches_in_proposal",
     "type": "graph",
     "description": "The number of transaction batches in a valid proposal received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_num_batches_in_proposal{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_num_txs_in_proposal",
     "type": "graph",
     "description": "The total number of individual transactions in a valid proposal received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_num_txs_in_proposal{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_inbound_stream_started",
     "type": "graph",
     "description": "The total number of inbound streams started",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_inbound_stream_started{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_inbound_stream_evicted",
     "type": "graph",
     "description": "The total number of inbound streams evicted due to cache capacity",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_inbound_stream_evicted{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_inbound_stream_finished",
     "type": "graph",
     "description": "The total number of inbound streams finished",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_inbound_stream_finished{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_outbound_stream_started",
     "type": "graph",
     "description": "The total number of outbound streams started",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_outbound_stream_started{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_outbound_stream_finished",
     "type": "graph",
     "description": "The total number of outbound streams finished",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_outbound_stream_finished{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_l2_gas_price",
     "type": "graph",
     "description": "The L2 gas price calculated in an accepted proposal",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_l2_gas_price{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "cende_last_prepared_blob_block_number",
     "type": "graph",
     "description": "The blob block number that cende knows. That means the sequencer can be the proposer only if the current height is greater by one than this value.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cende_last_prepared_blob_block_number{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "cende_prepare_blob_for_next_height_latency",
     "type": "graph",
     "description": "The time it takes to prepare the blob for the next height, i.e create the blob object.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(cende_prepare_blob_for_next_height_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "cende_write_prev_height_blob_latency",
     "type": "graph",
     "description": "Be careful with this metric, if the blob was already written by another request, the latency is much lower since writing to Aerospike is not needed.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(cende_write_prev_height_blob_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "cende_write_blob_success",
     "type": "graph",
     "description": "The number of successful blob writes to Aerospike",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cende_write_blob_success{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "cende_write_blob_failure",
     "type": "graph",
     "description": "The number of failed blob writes to Aerospike",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (cende_write_failure_reason) (cende_write_blob_failure{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "consensus_l1_data_gas_mismatch",
     "type": "graph",
     "description": "The number of times the L1 data gas in a proposal does not match the value expected by this validator",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_l1_data_gas_mismatch{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "consensus_l1_gas_mismatch",
     "type": "graph",
     "description": "The number of times the L1 gas in a proposal does not match the value expected by this validator",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_l1_gas_mismatch{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_server_added_transactions_total",
     "type": "graph",
     "description": "Total number of transactions added",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_server_added_transactions_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "State Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_state_sync_processed_transactions",
     "type": "stat",
     "description": "The number of transactions processed by the state sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_processed_transactions{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_state_sync_reverted_transactions",
     "type": "stat",
     "description": "The number of transactions reverted by the state sync component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_reverted_transactions{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_central_sync_central_block_marker",
     "type": "stat",
     "description": "The first block number that doesn't exist yet",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_central_sync_central_block_marker{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_state_sync_body_marker",
     "type": "stat",
     "description": "The first block number for which the state sync component does not have a body",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_body_marker{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_state_sync_class_manager_marker",
     "type": "stat",
     "description": "The first block number for which the state sync component does not guarantee all of the corresponding classes are stored in the class manager component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_class_manager_marker{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_state_sync_header_marker",
     "type": "stat",
     "description": "The first block number for which the state sync component does not have a header",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_header_marker{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_state_sync_state_marker",
     "type": "stat",
     "description": "The first block number for which the state sync component does not have a state body",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_state_sync_state_marker{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "MempoolP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_mempool_p2p_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_sent_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_received_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_broadcasted_transaction_batch_size",
     "type": "stat",
     "description": "The number of transactions in batches broadcast by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_broadcasted_transaction_batch_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "ConsensusP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_consensus_num_connected_peers",
     "type": "graph",
     "description": "The number of connected peers to the consensus p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_num_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_sent_messages",
     "type": "graph",
     "description": "The number of messages sent by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_sent_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_received_messages",
     "type": "graph",
     "description": "The number of messages received by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_received_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_sent_messages",
     "type": "graph",
     "description": "The number of messages sent by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_sent_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_received_messages",
     "type": "graph",
     "description": "The number of messages received by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_received_messages{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "StateSyncP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_p2p_sync_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_connected_peers{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_p2p_sync_num_active_inbound_sessions",
     "type": "stat",
     "description": "The number of inbound sessions to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_active_inbound_sessions{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "apollo_p2p_sync_num_active_outbound_sessions",
     "type": "stat",
     "description": "The number of outbound sessions to the p2p sync component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_p2p_sync_num_active_outbound_sessions{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (source) (gateway_transactions_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the gateway during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(gateway_transactions_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}[20m])) or vector(0)"
      }
     ]
    },
    {
     "title": "gateway_add_tx_latency",
     "type": "heatmap",
     "description": "Latency of gateway add_tx function in secs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(gateway_add_tx_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "gateway_validate_tx_latency",
     "type": "heatmap",
     "description": "Latency of gateway validate function in secs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(gateway_validate_tx_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "gateway_transactions_failed",
     "type": "stat",
     "description": "Counter of failed transactions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_failed{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "gateway_transactions_sent_to_mempool",
     "type": "stat",
     "description": "Counter of transactions sent to the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_sent_to_mempool{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received by the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (mempool_transactions_received{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "mempool_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the mempool during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(mempool_transactions_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}[20m])) or vector(0)"
      }
     ]
    },
    {
     "title": "mempool_transactions_dropped",
     "type": "stat",
     "description": "Counter of transactions dropped from the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (drop_reason) (mempool_transactions_dropped{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "mempool_txs_committed",
     "type": "stat",
     "description": "The number of transactions that were committed to block",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_txs_committed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_pool_size",
     "type": "graph",
     "description": "The average size of the pool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pool_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_priority_queue_size",
     "type": "graph",
     "description": "The average size of the priority queue",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_priority_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_pending_queue_size",
     "type": "graph",
     "description": "The average size of the pending queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pending_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_total_size_bytes",
     "type": "graph",
     "description": "The average total transaction size in bytes over time in the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_total_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_get_txs_size",
     "type": "graph",
     "description": "The average size of the get_txs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_get_txs_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_delayed_declare_size",
     "type": "graph",
     "description": "The average number of delayed declare transactions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_delayed_declare_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    },
    {
     "title": "mempool_transaction_time_spent",
     "type": "graph",
     "description": "The time (secs) that a transaction spent in the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_transaction_time_spent_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Blockifier State Reader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "class_cache_miss_ratio",
     "type": "graph",
     "description": "The ratio of cache misses when requesting compiled classes from the Blockifier State Reader",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "100 * (increase(class_cache_misses{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]) / (increase(class_cache_misses{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]) + increase(class_cache_hits{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])))"
      }
     ]
    },
    {
     "title": "native_class_returned_ratio",
     "type": "graph",
     "description": "The ratio of Native classes returned by the Blockifier State Reader",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "100 * (increase(native_class_returned{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]) / (increase(class_cache_hits{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]) + increase(class_cache_misses{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])))"
      }
     ]
    },
    {
     "title": "native_compilation_error",
     "type": "stat",
     "description": "Counter of Native compilation failures in the blockifier",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "native_compilation_error{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batcher Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "batcher_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by batcher local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by batcher local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_local_queue_depth",
     "type": "graph",
     "description": "The depth of the batcher's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by batcher remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "batcher_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a batcher remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "batcher_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "gateway_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by gateway local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by gateway local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_local_queue_depth",
     "type": "graph",
     "description": "The depth of the gateway's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by gateway remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "gateway_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a gateway remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gateway_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Class Manager Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "class_manager_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by class manager local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by class manager local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_local_queue_depth",
     "type": "graph",
     "description": "The depth of the class manager's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by class manager remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "class_manager_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a class manager remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 277 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "class_manager_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 Provider Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "l1_provider_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by L1 provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 278 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by L1 provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 278 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_local_queue_depth",
     "type": "graph",
     "description": "The depth of the L1 provider's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by L1 provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_provider_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a L1 provider remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_provider_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 Gas Price Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "l1_gas_price_provider_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by L1 gas price provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by L1 gas price provider local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_local_queue_depth",
     "type": "graph",
     "description": "The depth of the L1 gas price provider's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 303 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 303 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 309 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by L1 gas price provider remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 309 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "l1_gas_price_provider_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a L1 gas price provider remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 315 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "l1_gas_price_provider_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by mempool local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by mempool local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_local_queue_depth",
     "type": "graph",
     "description": "The depth of the mempool's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by mempool remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a mempool remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "MempoolP2pInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_p2p_propagator_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by mempool p2p local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 335 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by mempool p2p local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 335 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_local_queue_depth",
     "type": "graph",
     "description": "The depth of the mempool p2p's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 341 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 341 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by mempool p2p remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "mempool_p2p_propagator_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a mempool p2p remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 353 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mempool_p2p_propagator_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "SierraCompilerInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "sierra_compiler_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by sierra compiler local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by sierra compiler local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_local_queue_depth",
     "type": "graph",
     "description": "The depth of the sierra compiler's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by sierra compiler remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by sierra compiler remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 366 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by sierra compiler remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 366 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "sierra_compiler_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a sierra compiler remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sierra_compiler_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compile sierra to casm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "compile_to_casm_compilation_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "type": "graph",
     "description": "Server-side compilation to casm duration in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(compile_to_casm_compilation_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "StateSyncInfra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 373 },
   "collapsed": true,
   "panels": [
    {
     "title": "state_sync_local_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by state sync local server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_local_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_local_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by state sync local server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_local_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_local_queue_depth",
     "type": "graph",
     "description": "The depth of the state sync's local message queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_local_queue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_remote_msgs_received",
     "type": "graph",
     "description": "Counter of messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_remote_valid_msgs_received",
     "type": "graph",
     "description": "Counter of valid messages received by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_valid_msgs_received{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_remote_msgs_processed",
     "type": "graph",
     "description": "Counter of messages processed by state sync remote server",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_msgs_processed{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "state_sync_remote_client_send_attempts",
     "type": "graph",
     "description": "Required number of remote connection attempts made by a state sync remote client",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "state_sync_remote_client_send_attempts_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  }
 ]
}