{
 "title": "Sequencer Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "batcher_proposal_started",
     "type": "stat",
     "description": "Counter of proposals started",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_started" }
     ]
    },
    {
     "title": "batcher_proposal_succeeded",
     "type": "stat",
     "description": "Counter of successful proposals",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_succeeded" }
     ]
    },
    {
     "title": "batcher_proposal_failed",
     "type": "stat",
     "description": "Counter of failed proposals",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_proposal_failed" }
     ]
    },
    {
     "title": "batcher_batched_transactions",
     "type": "stat",
     "description": "Counter of batched transactions across all forks",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "batcher_batched_transactions" }
     ]
    },
    {
     "title": "cairo_native_cache_miss_ratio",
     "type": "graph",
     "description": "The ratio of cache misses in the Cairo native cache",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "100 * (class_cache_misses / clamp_min((class_cache_misses + class_cache_hits), 1))"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "consensus_block_number",
     "type": "stat",
     "description": "The block number consensus is working to decide",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_block_number" }
     ]
    },
    {
     "title": "consensus_round",
     "type": "stat",
     "description": "The round of the state machine",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_round" }
     ]
    },
    {
     "title": "consensus_max_cached_block_number",
     "type": "stat",
     "description": "How many blocks after current are cached",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_max_cached_block_number"
      }
     ]
    },
    {
     "title": "consensus_cached_votes",
     "type": "stat",
     "description": "How many votes are cached when starting to work on a new block number",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_cached_votes" }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_consensus",
     "type": "stat",
     "description": "The total number of decisions reached by way of consensus",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_consensus"
      }
     ]
    },
    {
     "title": "consensus_decisions_reached_by_sync",
     "type": "stat",
     "description": "The total number of decisions reached by way of sync",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_decisions_reached_by_sync"
      }
     ]
    },
    {
     "title": "consensus_proposals_received",
     "type": "stat",
     "description": "The total number of proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_received" }
     ]
    },
    {
     "title": "consensus_proposals_accepted_for_validation",
     "type": "stat",
     "description": "The number of proposal inits that passed initial checks and were accepted for validation",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_proposals_accepted_for_validation"
      }
     ]
    },
    {
     "title": "consensus_proposals_validated",
     "type": "stat",
     "description": "The total number of complete, valid proposals received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_validated" }
     ]
    },
    {
     "title": "consensus_proposals_invalid",
     "type": "stat",
     "description": "The total number of proposals that failed validation",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_proposals_invalid" }
     ]
    },
    {
     "title": "consensus_build_proposal_total",
     "type": "stat",
     "description": "The total number of proposals built",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_build_proposal_total" }
     ]
    },
    {
     "title": "consensus_build_proposal_failed",
     "type": "stat",
     "description": "The number of proposals that failed to be built",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_build_proposal_failed"
      }
     ]
    },
    {
     "title": "consensus_reproposals",
     "type": "stat",
     "description": "The number of reproposals sent",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "consensus_reproposals" }
     ]
    }
   ]
  },
  {
   "title": "Http Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_server_added_transactions_total",
     "type": "stat",
     "description": "Total number of transactions added",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_server_added_transactions_total"
      }
     ]
    }
   ]
  },
  {
   "title": "MempoolP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_mempool_p2p_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_mempool_p2p_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the mempool p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_mempool_p2p_num_received_messages"
      }
     ]
    }
   ]
  },
  {
   "title": "ConsensusP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_consensus_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the consensus p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_votes_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the consensus p2p component over the Votes topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_votes_num_received_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_sent_messages",
     "type": "stat",
     "description": "The number of messages sent by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_sent_messages"
      }
     ]
    },
    {
     "title": "apollo_consensus_proposals_num_received_messages",
     "type": "stat",
     "description": "The number of messages received by the consensus p2p component over the Proposals topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_consensus_proposals_num_received_messages"
      }
     ]
    }
   ]
  },
  {
   "title": "StateSyncP2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "apollo_sync_num_connected_peers",
     "type": "stat",
     "description": "The number of connected peers to the state sync p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_sync_num_connected_peers"
      }
     ]
    },
    {
     "title": "apollo_sync_num_active_inbound_sessions",
     "type": "stat",
     "description": "The number of inbound sessions to the state sync p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_sync_num_active_inbound_sessions"
      }
     ]
    },
    {
     "title": "apollo_sync_num_active_outbound_sessions",
     "type": "stat",
     "description": "The number of outbound sessions to the state sync p2p component",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_sync_num_active_outbound_sessions"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_received) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (source) (gateway_transactions_received) "
      }
     ]
    },
    {
     "title": "gateway_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the gateway during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(gateway_transactions_received[20m]))"
      }
     ]
    },
    {
     "title": "gateway_add_tx_latency",
     "type": "graph",
     "description": "Latency of gateway add_tx function in secs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(gateway_add_tx_latency[2m])"
      }
     ]
    },
    {
     "title": "gateway_transactions_failed",
     "type": "stat",
     "description": "Counter of failed transactions",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_failed)"
      }
     ]
    },
    {
     "title": "gateway_transactions_sent_to_mempool",
     "type": "stat",
     "description": "Counter of transactions sent to the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (gateway_transactions_sent_to_mempool)"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool_transactions_received",
     "type": "stat",
     "description": "Counter of transactions received by the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (tx_type) (mempool_transactions_received)"
      }
     ]
    },
    {
     "title": "mempool_transactions_received_rate (TPS)",
     "type": "graph",
     "description": "The rate of transactions received by the mempool during the last 20 minutes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(mempool_transactions_received[20m]))"
      }
     ]
    },
    {
     "title": "mempool_transactions_dropped",
     "type": "stat",
     "description": "Counter of transactions dropped from the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (drop_reason) (mempool_transactions_dropped)"
      }
     ]
    },
    {
     "title": "mempool_txs_committed",
     "type": "stat",
     "description": "The number of transactions that were committed to block",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "mempool_txs_committed" }
     ]
    },
    {
     "title": "mempool_pool_size",
     "type": "graph",
     "description": "The average size of the pool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pool_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_priority_queue_size",
     "type": "graph",
     "description": "The average size of the priority queue",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_priority_queue_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_pending_queue_size",
     "type": "graph",
     "description": "The average size of the pending queue",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_pending_queue_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_get_txs_size",
     "type": "graph",
     "description": "The average size of the get_txs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_get_txs_size[2m])"
      }
     ]
    },
    {
     "title": "mempool_transaction_time_spent",
     "type": "graph",
     "description": "The time (secs) that a transaction spent in the mempool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(mempool_transaction_time_spent[2m])"
      }
     ]
    }
   ]
  }
 ]
}