image:
  repository: ghcr.io/starkware-libs/sequencer/sequencer
  imagePullPolicy: IfNotPresent

config:
  sequencerConfig:
    eth_fee_token_address: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7'
    monitoring_endpoint_config.port: 8082
    strk_fee_token_address: '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d'
    versioned_constants_overrides.#is_none: true
    versioned_constants_overrides.max_n_events: 1000

service:
  ports:
  - name: monitoring-endpoint
    port: 8082
    targetPort: 8082
    protocol: TCP

startupProbe:
  enabled: true
  path: /monitoring/alive
  successThreshold: 1
  failureThreshold: 30
  periodSeconds: 5
  timeoutSeconds: 2

readinessProbe:
  enabled: true
  path: /monitoring/ready
  successThreshold: 2
  failureThreshold: 3
  periodSeconds: 5
  timeoutSeconds: 2

livenessProbe:
  enabled: true
  path: /monitoring/alive
  successThreshold: 1
  failureThreshold: 5
  periodSeconds: 10
  timeoutSeconds: 3

gcpPodMonitoring:
  enabled: true
  spec:
    endpoints:
    - port: 8082
      path: /monitoring/metrics
      interval: 10s

env:
- name: RUST_LOG
  value: debug
- name: RUST_BACKTRACE
  value: full
- name: NO_COLOR
  value: '1'
