include:
  - configs/overlays/hybrid/common/services/sierra-compiler.yaml
  - configs/overlays/hybrid/echonet/common.yaml

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "8Gi"
