use rstest::rstest;
use starknet_api::test_utils::{path_in_resources, read_json_file};
use starknet_api::transaction::fields::{Proof, ProofFacts, PROOF_VERSION};
use starknet_types_core::felt::Felt;

use crate::{reconstruct_output_preimage, verify_proof, ProgramOutput};

/// Verifies that converting ProgramOutput -> ProofFacts -> output preimage produces the
/// original program output.
#[test]
fn roundtrip_program_output_to_proof_facts_and_back() {
    let program_hash = Felt::from(0xABCD_u64);
    let task_output = [Felt::from(1_u64), Felt::from(2_u64), Felt::from(3_u64)];
    let task_content_len = 1 + task_output.len(); // program_hash + task_output
    let output_size = Felt::from(u64::try_from(task_content_len + 1).unwrap());

    let original_output: Vec<Felt> =
        [Felt::ONE, output_size, program_hash].into_iter().chain(task_output).collect();
    let program_output = ProgramOutput::from(original_output.clone());

    let program_variant = Felt::from(0x42_u64);
    let proof_facts = program_output.try_into_proof_facts(program_variant).unwrap();

    // Verify the proof facts structure: [PROOF_VERSION, variant, program_hash, ...task_output].
    assert_eq!(proof_facts.0[0], PROOF_VERSION);
    assert_eq!(proof_facts.0[1], program_variant);
    assert_eq!(proof_facts.0[2], program_hash);
    assert_eq!(&proof_facts.0[3..], &task_output);

    let reconstructed = reconstruct_output_preimage(&proof_facts).unwrap();
    assert_eq!(reconstructed, original_output);
}

/// Regression test: verifies that the current verifier can still accept proofs generated by
/// older prover versions. Each Starknet version has its own pinned proof resources under
/// `resources/regression_test/{version}/`.
///
/// To add a new version:
/// 1. Generate proof fixtures by running the `regenerate_proof_fixtures` test in
///    `starknet_transaction_prover`: ```bash cargo test -p starknet_transaction_prover --features
///    stwo_proving \ -- --ignored regenerate_proof_fixtures ```
/// 2. Copy the generated files into a new version directory: ```bash mkdir -p
///    crates/starknet_proof_verifier/resources/regression_test/{version} cp
///    crates/apollo_transaction_converter/resources/example_proof.bin \
///    crates/starknet_proof_verifier/resources/regression_test/{version}/ cp
///    crates/apollo_transaction_converter/resources/example_proof_facts.json \
///    crates/starknet_proof_verifier/resources/regression_test/{version}/ ```
/// 3. Add a new `#[case("{version}")]` below.
#[rstest]
#[case("0.14.2")]
fn regression_verify_proof_from_old_prover(#[case] starknet_version: &str) {
    let proof_path =
        path_in_resources(format!("regression_test/{starknet_version}/example_proof.bin"));
    let raw_bytes = std::fs::read(&proof_path)
        .unwrap_or_else(|e| panic!("Failed to read proof for version {starknet_version}: {e}"));
    let proof = Proof::from(raw_bytes);

    let proof_facts: ProofFacts =
        read_json_file(format!("regression_test/{starknet_version}/example_proof_facts.json"));

    verify_proof(proof_facts, proof).unwrap_or_else(|e| {
        panic!("Proof verification failed for version {starknet_version}: {e}")
    });
}
