apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echonet-data
  labels:
    app.kubernetes.io/name: echonet
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hyperdisk-balanced-baseline
  resources:
    requests:
      storage: 100Gi
