include: configs/overlays/hybrid/common/services/gateway.yaml

name: gateway
config:
  sequencerConfig:
    gateway_config.static_config.proof_archive_writer_config.bucket_name: starkware-starknet-integration
