include: configs/overlays/hybrid/common/services/l1.yaml

config:
  sequencerConfig:
    l1_gas_price_provider_config.chainlink_oracle_config.eth_usd_feed_address: '0x06b2ef9b416ad0f996b2a8ac0dd771b1788196f51c96f5b000df2e47ac756d26'
    l1_gas_price_provider_config.chainlink_oracle_config.strk_usd_feed_address: '0x076a0254cdadb59b86da3b5960bf8d73779cac88edc5ae587cab3cedf03226ec'
    base_layer_config.bpo1_start_block_number: 9456501
    base_layer_config.bpo2_start_block_number: 9504747
    base_layer_config.fusaka_no_bpo_start_block_number: 9408577
    base_layer_config.starknet_contract_address: '0x4737c0c1B4D5b1A687B42610DdabEE781152359c'
