apiVersion: v1
kind: Service
metadata:
  name: signature-manager
  labels:
    app.kubernetes.io/name: signature-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: signature-manager
  ports:
    - name: signing-http
      port: 9090
      targetPort: signing-http
      protocol: TCP
