apiVersion: v1
kind: Service
metadata:
  name: validation-node-monitoring
  labels:
    app.kubernetes.io/name: validation-node
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: validation-node
  ports:
    - name: monitoring
      port: 8082
      targetPort: monitoring
      protocol: TCP
