name: Apollo-Storage-OS-Input-CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - ".github/actions/bootstrap/action.yml"
      - ".github/workflows/apollo_storage_os_input_ci.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/apollo_storage/**"
      - "crates/apollo_config/**"
      - "crates/apollo_infra_utils/**"
      - "crates/apollo_metrics/**"
      - "crates/apollo_proc_macros/**"
      - "crates/apollo_test_utils/**"
      - "crates/blockifier/**"
      - "crates/starknet_api/**"

env:
  RUSTFLAGS: "-D warnings"

# On PR events, cancel existing CI runs on this same PR for this workflow.
# Also, create different concurrency groups for different pushed commits, on push events.
concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ github.event_name == 'pull_request' && 'PR' || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # https://graphite.com/docs/stacking-and-ci
  optimize_ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@v0.0.9
        with:
          graphite_token: ${{ secrets.GRAPHITE_CI_OPTIMIZER_TOKEN }}

  test-with-os-input-feature:
    runs-on: namespace-profile-medium-ubuntu-24-04-amd64
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/bootstrap
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo build -p apollo_batcher --features os_input
      - run: cargo test -p apollo_batcher --features os_input
      - run: cargo test -p apollo_reverts --features os_input
      - run: cargo test -p apollo_storage --features os_input
