name: Main-CI-PR-Flow

on:
  merge_group:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  RUSTFLAGS: "-D warnings"

# On PR events, cancel existing CI runs on this same PR for this workflow.
# Also, create different concurrency groups for different pushed commits, on push events.
concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ github.event_name == 'pull_request' && 'PR' || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # This job is used to check if all checks have passed before merging the PR.
  # Uses starkware-libs/merge-gatekeeper as the implementation.
  merge-gatekeeper-new:
    runs-on: ubuntu-24.04
    timeout-minutes: 75
    permissions:
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Run merge-gatekeeper-new on pull request
        if: github.event_name == 'pull_request'
        uses: starkware-libs/merge-gatekeeper@c0535e7c50a3fc70a0f4857afd37ccd6cfcc59de # v1
        with:
          self: merge-gatekeeper-new
          timeout: 3600
          interval: 30
          ignored: "code-review/reviewable,build_docker_images"

      - name: Run merge-gatekeeper-new on Merge Queue || push
        if: github.event_name == 'merge_group' || github.event_name == 'push'
        uses: starkware-libs/merge-gatekeeper@c0535e7c50a3fc70a0f4857afd37ccd6cfcc59de # v1
        with:
          self: merge-gatekeeper-new
          ref: ${{github.ref}}
          timeout: 1800
          interval: 30
          ignored: "code-review/reviewable"
