name: Main-CI-PR-Flow

on:
  merge_group:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  RUSTFLAGS: "-D warnings"

# On PR events, cancel existing CI runs on this same PR for this workflow.
# Also, create different concurrency groups for different pushed commits, on push events.
concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ github.event_name == 'pull_request' && 'PR' || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Validate PR title with commitlint
        if: github.event_name != 'merge_group' && github.event_name != 'push' && !(contains(github.event.pull_request.title, 'merge-main') || contains(github.event.pull_request.title, 'merge main'))
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | commitlint --verbose

  # This job is used to check if all checks have passed before merging the PR.
  # It is a replacement candidate for merge-gatekeeper.
  # Currently running in "observer" mode.
  all-checks-passed:
    runs-on: ubuntu-24.04
    permissions:
      checks: read
      contents: read
      statuses: read
    steps:
      - uses: wechuli/allcheckspassed@v2
        with:
          checks_exclude: "code-review/reviewable,merge-gatekeeper"
          delay: 0 # start checking immediately
          retries: 120 # 120 * 30 = 3600 seconds ( 60 minutes timeout )
          polling_interval: 0.5 # check every 30 seconds
          fail_fast: false # Wait for all checks to complete before failing the job
          verbose: true
          show_job_summary: true
          treat_skipped_as_passed: true # If any check is skipped, treat it as passed

  merge-gatekeeper:
    runs-on: ubuntu-24.04
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper on pull request
        if: github.event_name == 'pull_request'
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 3600
          interval: 30
          ignored: "code-review/reviewable,build_docker_images,all-checks-passed"

      - name: Run Merge Gatekeeper on Merge Queue || push
        if: github.event_name == 'merge_group' || github.event_name == 'push'
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{github.ref}}
          timeout: 1800
          interval: 30
          ignored: "code-review/reviewable,all-checks-passed"
