name: Starknet-OS-Runner-Prover-CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/starknet_os_runner_ci.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/blockifier/**"
      - "crates/blockifier_reexecution/**"
      - "crates/starknet_os_runner/**"
      - "crates/starknet_os/**"
      - "crates/starknet_committer/**"
      - "crates/starknet_patricia/**"
      - "crates/proving_utils/**"
      - "scripts/dependencies.sh"
      - "scripts/install_build_tools.sh"
      - "scripts/install_stwo_run_and_prove.sh"
      - "scripts/proving_utils_env.sh"
      - "scripts/sequencer-ci.Dockerfile"

env:
  RUSTFLAGS: "-D warnings"

concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ github.event_name == 'pull_request' && 'PR' || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  starknet_os_runner_prover:
    runs-on: namespace-profile-xlarge-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/bootstrap
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Setup pypy and link to the location expected by .cargo/config.toml.
      # Python + requirements are needed to compile the OS.
      - uses: actions/setup-python@v5
        id: setup-pypy
        with:
          python-version: "pypy3.9"
          cache: "pip"
          cache-dependency-path: scripts/requirements.txt
      - run: ln -s '${{ steps.setup-pypy.outputs.python-path }}' /usr/local/bin/pypy3.9
      - env:
          LD_LIBRARY_PATH: ${{ env.Python3_ROOT_DIR }}/bin
        run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
      - run: pip install -r scripts/requirements.txt

      - name: Cache prover builds
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            build/proving-utils
            target/tools

      - name: Install stwo_run_and_prove
        run: SKIP_BUILD_IF_EXISTS=1 ./scripts/install_stwo_run_and_prove.sh

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.SA_STARKNET_OS_RUNNER_ARTIFACTS }}
      - uses: "google-github-actions/setup-gcloud@v2"
      - run: mkdir -p ./crates/starknet_os_runner/resources/rpc_records
      - run: gcloud storage cp -r gs://starknet-os-runner-artifacts/rpc_records/* ./crates/starknet_os_runner/resources/rpc_records/

      - name: "Test: prove balance_of transaction"
        run: cargo test --release -p starknet_os_runner test_prove_balance_of_transaction -- --ignored
      - name: "Test: prove transfer transaction"
        run: cargo test --release -p starknet_os_runner test_prove_transfer_transaction -- --ignored
